[paths]
input_dir = 'C:\Users\CND367\Documents\WaSP\test2_nd'
processed_dir = 'C:\Users\CND367\Documents\WaSP\test2_nd\processed'
figures_dir = 'C:\Users\CND367\Documents\WaSP\test2_nd\figures'

[files]
sp_data = 'formatted_self_potential.csv'
drift_data = ''
temp_cond_data = 'formatted_conductivity.csv'
hfem_resistivity = ''

[processing]
dipole_length_m = 0.5
gaussian_sigma = 30
boxcar_m = 5
boxcar_iterations = 1