[paths]
input_dir = 'C:\Users\CND367\Documents\WaSP\test2'
processed_dir = 'C:\Users\CND367\Documents\WaSP\test2\processed'
figures_dir = 'C:\Users\CND367\Documents\WaSP\test2\figures'

[files]
sp_data = 'formatted_self_potential.csv'
drift_data = 'drift_self_potential.csv'
temp_cond_data = 'formatted_conductivity.csv'
hfem_resistivity = ''

[processing]
dipole_length_m = 0.5
gaussian_sigma = 30
boxcar_m = 5
boxcar_iterations = 1